/**
 * Elementa — 30 neue Komponenten seeden (5 pro Kategorie).
 * Start: APPWRITE_API_KEY="<key>" node scripts/seed-new.mjs
 *
 * likesCount = 0 (Wahrheitsregel; echte Likes kommen aus der likes-Collection).
 * a11y: buttons/inputs/toggles = "pass", sonst "unchecked".
 */
import { Client, Databases, Permission, Role, ID } from "node-appwrite";

const endpoint = process.env.APPWRITE_ENDPOINT || "https://appwrite.it-handwerk-stuttgart.de/v1";
const project = process.env.APPWRITE_PROJECT || "6a4453770009b9e7f029";
const apiKey = process.env.APPWRITE_API_KEY;
if (!apiKey) { console.error("APPWRITE_API_KEY fehlt."); process.exit(1); }

const AUTHOR_ID = "6a447115002c7120de36";
const AUTHOR_NAME = "Belkis";
const DB = "marketplace";
const COL = "components";

const client = new Client().setEndpoint(endpoint).setProject(project).setKey(apiKey);
const db = new Databases(client);
const perms = [
  Permission.read(Role.any()),
  Permission.update(Role.user(AUTHOR_ID)),
  Permission.delete(Role.user(AUTHOR_ID)),
];

// Agenten liefern strukturelle Zeichen als Entities — hier zurückwandeln.
const unesc = (s) => (s || "").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");

const BUTTONS = [
  {"slug":"gradient-frame-button","title":"Animated Gradient Frame Button","description":"Ein Button mit rotierendem Verlaufsrahmen aus Violett, Fuchsia und Cyan, der durch die kontinuierliche Drehung Aufmerksamkeit erzeugt und wichtige Call-to-Actions hervorhebt.","framework":"css","tags":["gradient","border","animated","neon","cta"],"html":"&lt;button class=\"btn-grad-frame-a1\"&gt;&lt;span&gt;Jetzt starten&lt;/span&gt;&lt;/button&gt;","css":"button.btn-grad-frame-a1{position:relative;border:none;cursor:pointer;padding:14px 30px;border-radius:12px;background:#12121c;color:#fff;font:600 15px/1 system-ui,-apple-system,sans-serif;letter-spacing:.3px;isolation:isolate;transition:background .25s;}\nbutton.btn-grad-frame-a1 span{position:relative;z-index:1;}\nbutton.btn-grad-frame-a1::before{content:\"\";position:absolute;inset:-2px;border-radius:14px;padding:2px;background:conic-gradient(from var(--a1,0deg),#8b5cf6,#d946ef,#06b6d4,#8b5cf6);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;z-index:-1;animation:spin-a1 4s linear infinite;}\n@property --a1{syntax:\"&lt;angle&gt;\";inherits:false;initial-value:0deg;}\n@keyframes spin-a1{to{--a1:360deg;}}\nbutton.btn-grad-frame-a1:hover{background:#191926;}\nbutton.btn-grad-frame-a1:focus-visible{outline:2px solid #06b6d4;outline-offset:3px;}\n@media (prefers-reduced-motion:reduce){button.btn-grad-frame-a1::before{animation:none;}}","js":""},
  {"slug":"glow-pulse-button","title":"Glow Pulse Button","description":"Ein Button mit weichem, pulsierendem Neon-Glow in Violett und Fuchsia, der auf dunklem Hintergrund lebendig leuchtet und den Nutzer sanft zur Interaktion einlädt.","framework":"css","tags":["glow","pulse","gradient","neon","shadow"],"html":"&lt;button class=\"btn-glow-pulse-b2\"&gt;Mehr entdecken&lt;/button&gt;","css":"button.btn-glow-pulse-b2{border:none;cursor:pointer;padding:14px 32px;border-radius:12px;color:#fff;font:600 15px/1 system-ui,-apple-system,sans-serif;letter-spacing:.3px;background:linear-gradient(135deg,#8b5cf6,#d946ef);animation:glow-b2 2.4s ease-in-out infinite;transition:transform .2s;}\n@keyframes glow-b2{0%,100%{box-shadow:0 0 18px rgba(139,92,246,.45),0 0 4px rgba(217,70,239,.4);}50%{box-shadow:0 0 34px rgba(217,70,239,.7),0 0 12px rgba(139,92,246,.6);}}\nbutton.btn-glow-pulse-b2:hover{transform:translateY(-2px);}\nbutton.btn-glow-pulse-b2:active{transform:translateY(0);}\nbutton.btn-glow-pulse-b2:focus-visible{outline:2px solid #fff;outline-offset:3px;}\n@media (prefers-reduced-motion:reduce){button.btn-glow-pulse-b2{animation:none;box-shadow:0 0 22px rgba(139,92,246,.5);}}","js":""},
  {"slug":"shine-sweep-button","title":"Shine Sweep Button","description":"Ein Button mit einem eleganten Licht-Reflex, der in regelmäßigen Abständen diagonal über die Cyan-Violett-Fläche gleitet und dem Element eine hochwertige, glänzende Anmutung verleiht.","framework":"css","tags":["shine","sweep","gradient","glossy","reflection"],"html":"&lt;button class=\"btn-shine-sweep-c3\"&gt;&lt;span&gt;Premium holen&lt;/span&gt;&lt;/button&gt;","css":"button.btn-shine-sweep-c3{position:relative;overflow:hidden;border:none;cursor:pointer;padding:14px 32px;border-radius:12px;color:#fff;font:600 15px/1 system-ui,-apple-system,sans-serif;letter-spacing:.3px;background:linear-gradient(135deg,#06b6d4,#8b5cf6);transition:filter .25s;}\nbutton.btn-shine-sweep-c3 span{position:relative;z-index:1;}\nbutton.btn-shine-sweep-c3::after{content:\"\";position:absolute;top:0;left:-120%;width:60%;height:100%;background:linear-gradient(120deg,transparent,rgba(255,255,255,.55),transparent);transform:skewX(-20deg);animation:sweep-c3 3s ease-in-out infinite;}\n@keyframes sweep-c3{0%{left:-120%;}45%,100%{left:160%;}}\nbutton.btn-shine-sweep-c3:hover{filter:brightness(1.1);}\nbutton.btn-shine-sweep-c3:focus-visible{outline:2px solid #06b6d4;outline-offset:3px;}\n@media (prefers-reduced-motion:reduce){button.btn-shine-sweep-c3::after{display:none;}}","js":""},
  {"slug":"ripple-wave-button","title":"Ripple Wave Button","description":"Ein Button, der bei jedem Klick eine kreisförmige Wellen-Animation vom Klickpunkt aus erzeugt und so ein taktiles, materielles Feedback für den Nutzer liefert.","framework":"css","tags":["ripple","wave","interaction","feedback","gradient"],"html":"&lt;button class=\"btn-ripple-d4\"&gt;&lt;span&gt;Anklicken&lt;/span&gt;&lt;/button&gt;","css":"button.btn-ripple-d4{position:relative;overflow:hidden;border:none;cursor:pointer;padding:14px 34px;border-radius:12px;color:#fff;font:600 15px/1 system-ui,-apple-system,sans-serif;letter-spacing:.3px;background:linear-gradient(135deg,#8b5cf6,#06b6d4);}\nbutton.btn-ripple-d4 span{position:relative;z-index:1;}\nbutton.btn-ripple-d4 .rp-d4{position:absolute;border-radius:50%;transform:translate(-50%,-50%) scale(0);background:rgba(255,255,255,.45);pointer-events:none;animation:ripple-d4 .6s ease-out forwards;}\n@keyframes ripple-d4{to{transform:translate(-50%,-50%) scale(1);opacity:0;}}\nbutton.btn-ripple-d4:hover{filter:brightness(1.08);}\nbutton.btn-ripple-d4:focus-visible{outline:2px solid #d946ef;outline-offset:3px;}\n@media (prefers-reduced-motion:reduce){button.btn-ripple-d4 .rp-d4{animation-duration:.01ms;}}","js":"document.querySelectorAll('.btn-ripple-d4').forEach(function(b){b.addEventListener('click',function(e){var r=document.createElement('span');r.className='rp-d4';var d=Math.max(b.clientWidth,b.clientHeight);var rect=b.getBoundingClientRect();r.style.width=r.style.height=d+'px';r.style.left=(e.clientX-rect.left)+'px';r.style.top=(e.clientY-rect.top)+'px';b.appendChild(r);setTimeout(function(){r.remove();},600);});});"},
  {"slug":"arrow-slide-button","title":"Arrow Slide Button","description":"Ein Ghost-Button, der beim Hovern in einen Violett-Fuchsia-Verlauf übergeht und dessen Pfeil-Icon nach rechts gleitet, um dem Nutzer die Fortsetzung der Aktion zu signalisieren.","framework":"css","tags":["arrow","slide","ghost","hover","gradient"],"html":"&lt;button class=\"btn-arrow-slide-e5\"&gt;&lt;span class=\"lbl-e5\"&gt;Weiter&lt;/span&gt;&lt;svg class=\"arw-e5\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"&gt;&lt;line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"/&gt;&lt;polyline points=\"12 5 19 12 12 19\"/&gt;&lt;/svg&gt;&lt;/button&gt;","css":"button.btn-arrow-slide-e5{position:relative;border:1px solid rgba(139,92,246,.5);cursor:pointer;padding:14px 26px;border-radius:12px;color:#fff;font:600 15px/1 system-ui,-apple-system,sans-serif;letter-spacing:.3px;background:#12121c;display:inline-flex;align-items:center;gap:10px;transition:background .3s,border-color .3s,box-shadow .3s;}\nbutton.btn-arrow-slide-e5 .arw-e5{width:18px;height:18px;transition:transform .3s;}\nbutton.btn-arrow-slide-e5:hover{background:linear-gradient(135deg,#8b5cf6,#d946ef);border-color:transparent;box-shadow:0 0 22px rgba(217,70,239,.4);}\nbutton.btn-arrow-slide-e5:hover .arw-e5{transform:translateX(5px);}\nbutton.btn-arrow-slide-e5:focus-visible{outline:2px solid #d946ef;outline-offset:3px;}\n@media (prefers-reduced-motion:reduce){button.btn-arrow-slide-e5,button.btn-arrow-slide-e5 .arw-e5{transition:none;}}","js":""}
];

const CARDS = [
  {"slug":"glass-frost-card","title":"Glass Frost Card","description":"Eine elegante Glassmorphism-Karte mit sanftem Blur-Effekt, feiner Randbeleuchtung und einem dezenten violetten Farbverlauf im Hintergrund.","framework":"css","tags":["glassmorphism","card","blur","dark","gradient"],"html":"&lt;div class=\"el-glass-frost\"&gt;\n  &lt;div class=\"el-glass-frost__glow\"&gt;&lt;/div&gt;\n  &lt;div class=\"el-glass-frost__body\"&gt;\n    &lt;span class=\"el-glass-frost__badge\"&gt;Pro&lt;/span&gt;\n    &lt;h3 class=\"el-glass-frost__title\"&gt;Frosted Panel&lt;/h3&gt;\n    &lt;p class=\"el-glass-frost__text\"&gt;Klare Sicht durch mattes Glas mit sanftem Lichtschimmer.&lt;/p&gt;\n    &lt;button class=\"el-glass-frost__btn\"&gt;Entdecken&lt;/button&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".el-glass-frost{position:relative;width:280px;height:180px;border-radius:18px;overflow:hidden;font-family:system-ui,sans-serif;isolation:isolate}\n.el-glass-frost__glow{position:absolute;inset:0;background:radial-gradient(120px 120px at 20% 15%,#8b5cf6,transparent 70%),radial-gradient(140px 140px at 85% 90%,#06b6d4,transparent 70%);filter:blur(6px);z-index:0}\n.el-glass-frost__body{position:absolute;inset:1px;border-radius:17px;padding:18px;background:rgba(20,18,34,.55);backdrop-filter:blur(14px) saturate(140%);-webkit-backdrop-filter:blur(14px) saturate(140%);border:1px solid rgba(255,255,255,.12);box-shadow:inset 0 1px 0 rgba(255,255,255,.15);z-index:1;display:flex;flex-direction:column}\n.el-glass-frost__badge{align-self:flex-start;font-size:11px;font-weight:600;color:#e9d5ff;padding:3px 10px;border-radius:999px;background:rgba(139,92,246,.25);border:1px solid rgba(139,92,246,.4)}\n.el-glass-frost__title{margin:12px 0 4px;font-size:19px;color:#fff;font-weight:700}\n.el-glass-frost__text{margin:0;font-size:12.5px;line-height:1.5;color:rgba(226,224,240,.75);flex:1}\n.el-glass-frost__btn{align-self:flex-start;margin-top:10px;padding:7px 16px;font-size:12.5px;font-weight:600;color:#fff;border:none;border-radius:10px;cursor:pointer;background:linear-gradient(90deg,#8b5cf6,#d946ef);transition:transform .2s,box-shadow .2s}\n.el-glass-frost__btn:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgba(139,92,246,.5)}","js":""},
  {"slug":"spotlight-hover-card","title":"Spotlight Hover Card","description":"Eine interaktive Karte, die dem Mauszeiger mit einem weichen Lichtkegel folgt und so ein lebendiges Spotlight-Erlebnis auf dunklem Grund erzeugt.","framework":"css","tags":["spotlight","hover","interactive","card","cursor"],"html":"&lt;div class=\"el-spot\" onmousemove=\"this.style.setProperty('--mx',event.offsetX+'px');this.style.setProperty('--my',event.offsetY+'px')\"&gt;\n  &lt;div class=\"el-spot__light\"&gt;&lt;/div&gt;\n  &lt;div class=\"el-spot__content\"&gt;\n    &lt;div class=\"el-spot__icon\"&gt;✦&lt;/div&gt;\n    &lt;h3 class=\"el-spot__title\"&gt;Spotlight&lt;/h3&gt;\n    &lt;p class=\"el-spot__text\"&gt;Bewege die Maus über die Karte und folge dem Licht.&lt;/p&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".el-spot{--mx:50%;--my:50%;position:relative;width:280px;height:180px;border-radius:18px;overflow:hidden;background:#12101c;border:1px solid rgba(255,255,255,.08);font-family:system-ui,sans-serif;cursor:pointer}\n.el-spot__light{position:absolute;inset:0;background:radial-gradient(180px 180px at var(--mx) var(--my),rgba(217,70,239,.28),rgba(139,92,246,.14) 40%,transparent 70%);opacity:0;transition:opacity .3s}\n.el-spot:hover .el-spot__light{opacity:1}\n.el-spot__content{position:relative;z-index:1;padding:20px;height:100%;box-sizing:border-box;display:flex;flex-direction:column;justify-content:flex-end}\n.el-spot__icon{position:absolute;top:18px;right:20px;font-size:22px;color:#d946ef}\n.el-spot__title{margin:0 0 6px;font-size:20px;font-weight:700;color:#fff}\n.el-spot__text{margin:0;font-size:12.5px;line-height:1.5;color:rgba(226,224,240,.7)}","js":""},
  {"slug":"animated-gradient-border-card","title":"Animated Gradient Border Card","description":"Eine Karte mit einem umlaufenden, animierten Farbverlaufsrahmen in Violett, Fuchsia und Cyan, der sich sanft und endlos um den Inhalt dreht.","framework":"css","tags":["gradient","border","animated","card","glow"],"html":"&lt;div class=\"el-gborder\"&gt;\n  &lt;div class=\"el-gborder__inner\"&gt;\n    &lt;h3 class=\"el-gborder__title\"&gt;Aurora Edge&lt;/h3&gt;\n    &lt;p class=\"el-gborder__text\"&gt;Ein lebendiger Rahmen, der niemals stillsteht.&lt;/p&gt;\n    &lt;div class=\"el-gborder__meta\"&gt;&lt;span class=\"el-gborder__dot\"&gt;&lt;/span&gt;Live-Verlauf&lt;/div&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".el-gborder{position:relative;width:280px;height:180px;border-radius:18px;padding:2px;font-family:system-ui,sans-serif;background:conic-gradient(from 0deg,#8b5cf6,#d946ef,#06b6d4,#8b5cf6);animation:el-gborder-spin 4s linear infinite;box-shadow:0 0 26px rgba(139,92,246,.35)}\n@keyframes el-gborder-spin{to{transform:rotate(360deg)}}\n.el-gborder__inner{position:relative;height:100%;border-radius:16px;background:#100e18;padding:20px;box-sizing:border-box;display:flex;flex-direction:column;animation:el-gborder-spin 4s linear infinite reverse}\n.el-gborder__title{margin:0 0 6px;font-size:20px;font-weight:700;color:#fff}\n.el-gborder__text{margin:0;font-size:12.5px;line-height:1.5;color:rgba(226,224,240,.72);flex:1}\n.el-gborder__meta{display:flex;align-items:center;gap:8px;font-size:12px;color:#a5f3fc}\n.el-gborder__dot{width:8px;height:8px;border-radius:50%;background:#06b6d4;box-shadow:0 0 8px #06b6d4;animation:el-gborder-pulse 1.4s ease-in-out infinite}\n@keyframes el-gborder-pulse{0%,100%{opacity:1}50%{opacity:.3}}","js":""},
  {"slug":"tilt-3d-card","title":"3D Tilt Card","description":"Eine reine CSS-Karte mit räumlichem 3D-Neigungseffekt beim Überfahren, schwebender Ebene und farbigem Schlagschatten für eine plastische Tiefenwirkung.","framework":"css","tags":["3d","tilt","hover","card","perspective"],"html":"&lt;div class=\"el-tilt\"&gt;\n  &lt;div class=\"el-tilt__card\"&gt;\n    &lt;div class=\"el-tilt__shine\"&gt;&lt;/div&gt;\n    &lt;div class=\"el-tilt__layer\"&gt;\n      &lt;div class=\"el-tilt__chip\"&gt;3D&lt;/div&gt;\n      &lt;h3 class=\"el-tilt__title\"&gt;Depth Card&lt;/h3&gt;\n      &lt;p class=\"el-tilt__text\"&gt;Neige mich mit dem Zeiger für echte Tiefe.&lt;/p&gt;\n    &lt;/div&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".el-tilt{width:280px;height:180px;perspective:800px;font-family:system-ui,sans-serif}\n.el-tilt__card{position:relative;width:100%;height:100%;border-radius:18px;background:linear-gradient(150deg,#1a1430,#0f0d1a);border:1px solid rgba(255,255,255,.08);transform-style:preserve-3d;transition:transform .35s ease,box-shadow .35s ease;box-shadow:0 12px 30px rgba(0,0,0,.5)}\n.el-tilt:hover .el-tilt__card{transform:rotateX(9deg) rotateY(-12deg) scale(1.03);box-shadow:-18px 24px 45px rgba(139,92,246,.35)}\n.el-tilt__shine{position:absolute;inset:0;border-radius:18px;background:radial-gradient(160px 120px at 75% 15%,rgba(217,70,239,.3),transparent 60%);opacity:0;transition:opacity .35s}\n.el-tilt:hover .el-tilt__shine{opacity:1}\n.el-tilt__layer{position:relative;padding:20px;height:100%;box-sizing:border-box;display:flex;flex-direction:column;transform:translateZ(40px);transition:transform .35s}\n.el-tilt__chip{align-self:flex-start;font-size:11px;font-weight:700;color:#fff;padding:4px 10px;border-radius:8px;background:linear-gradient(90deg,#8b5cf6,#06b6d4)}\n.el-tilt__title{margin:12px 0 5px;font-size:20px;font-weight:700;color:#fff}\n.el-tilt__text{margin:0;font-size:12.5px;line-height:1.5;color:rgba(226,224,240,.7)}","js":""},
  {"slug":"glow-stat-card","title":"Glow Stat Card","description":"Eine kompakte Statistik-Karte mit leuchtender Kennzahl, grünem Erfolgs-Trend und einem sanften Neon-Glühen beim Überfahren für Dashboards.","framework":"css","tags":["stat","dashboard","glow","card","metric"],"html":"&lt;div class=\"el-stat\"&gt;\n  &lt;div class=\"el-stat__head\"&gt;\n    &lt;span class=\"el-stat__label\"&gt;Umsatz&lt;/span&gt;\n    &lt;span class=\"el-stat__trend\"&gt;▲ 12,4%&lt;/span&gt;\n  &lt;/div&gt;\n  &lt;div class=\"el-stat__value\"&gt;€ 48.920&lt;/div&gt;\n  &lt;div class=\"el-stat__bar\"&gt;&lt;span style=\"width:72%\"&gt;&lt;/span&gt;&lt;/div&gt;\n  &lt;div class=\"el-stat__foot\"&gt;Ziel zu 72% erreicht&lt;/div&gt;\n&lt;/div&gt;","css":".el-stat{width:280px;height:180px;box-sizing:border-box;border-radius:18px;padding:20px;font-family:system-ui,sans-serif;background:linear-gradient(160deg,#151228,#0e0c17);border:1px solid rgba(255,255,255,.08);display:flex;flex-direction:column;transition:box-shadow .3s,border-color .3s}\n.el-stat:hover{border-color:rgba(139,92,246,.5);box-shadow:0 0 30px rgba(139,92,246,.4)}\n.el-stat__head{display:flex;justify-content:space-between;align-items:center}\n.el-stat__label{font-size:12.5px;color:rgba(226,224,240,.65);letter-spacing:.3px}\n.el-stat__trend{font-size:12px;font-weight:700;color:#10b981;background:rgba(16,185,129,.14);padding:3px 9px;border-radius:999px}\n.el-stat__value{margin:14px 0 4px;font-size:32px;font-weight:800;background:linear-gradient(90deg,#8b5cf6,#d946ef);-webkit-background-clip:text;background-clip:text;color:transparent}\n.el-stat__bar{height:7px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden;margin-top:6px}\n.el-stat__bar span{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,#06b6d4,#8b5cf6);box-shadow:0 0 10px rgba(139,92,246,.6)}\n.el-stat__foot{margin-top:auto;font-size:11.5px;color:rgba(226,224,240,.55)}","js":""}
];

const LOADERS = [
  {"slug":"orbit-spinner-elementa","title":"Orbit Spinner","description":"Ein Orbit-Spinner im Dark-Theme, bei dem drei leuchtende Punkte auf konzentrischen Bahnen um ein violettes Zentrum kreisen und so einen eleganten Ladeeffekt erzeugen.","framework":"css","tags":["loader","spinner","orbit","dark","css"],"html":"&lt;div class=\"elx-orbit\" role=\"status\" aria-label=\"Laden\"&gt;\n  &lt;span class=\"elx-orbit__core\"&gt;&lt;/span&gt;\n  &lt;span class=\"elx-orbit__ring elx-orbit__ring--1\"&gt;&lt;i&gt;&lt;/i&gt;&lt;/span&gt;\n  &lt;span class=\"elx-orbit__ring elx-orbit__ring--2\"&gt;&lt;i&gt;&lt;/i&gt;&lt;/span&gt;\n  &lt;span class=\"elx-orbit__ring elx-orbit__ring--3\"&gt;&lt;i&gt;&lt;/i&gt;&lt;/span&gt;\n&lt;/div&gt;","css":".elx-orbit{position:relative;width:70px;height:70px;display:grid;place-items:center;background:#0b0b12;margin:auto}\n.elx-orbit__core{position:absolute;width:14px;height:14px;border-radius:50%;background:radial-gradient(circle at 30% 30%,#d946ef,#8b5cf6);box-shadow:0 0 12px #8b5cf6}\n.elx-orbit__ring{position:absolute;inset:0;border-radius:50%;animation:elx-orbit-spin 1.6s linear infinite}\n.elx-orbit__ring--2{inset:10px;animation-duration:2.2s;animation-direction:reverse}\n.elx-orbit__ring--3{inset:20px;animation-duration:2.8s}\n.elx-orbit__ring i{position:absolute;top:-3px;left:50%;width:8px;height:8px;margin-left:-4px;border-radius:50%;background:#06b6d4;box-shadow:0 0 8px #06b6d4}\n.elx-orbit__ring--2 i{background:#8b5cf6;box-shadow:0 0 8px #8b5cf6}\n.elx-orbit__ring--3 i{background:#d946ef;box-shadow:0 0 8px #d946ef}\n@keyframes elx-orbit-spin{to{transform:rotate(360deg)}}\n@media (prefers-reduced-motion:reduce){.elx-orbit__ring{animation:none}.elx-orbit__ring--2{transform:rotate(120deg)}.elx-orbit__ring--3{transform:rotate(240deg)}}","js":""},
  {"slug":"bouncing-dots-elementa","title":"Bouncing Dots","description":"Drei springende Punkte in den Elementa-Markenfarben bewegen sich versetzt auf und ab, um einen freundlichen und verspielten Ladezustand im dunklen Design darzustellen.","framework":"css","tags":["loader","dots","bounce","dark","css"],"html":"&lt;div class=\"elx-dots\" role=\"status\" aria-label=\"Laden\"&gt;\n  &lt;span&gt;&lt;/span&gt;\n  &lt;span&gt;&lt;/span&gt;\n  &lt;span&gt;&lt;/span&gt;\n&lt;/div&gt;","css":".elx-dots{display:flex;gap:10px;align-items:flex-end;height:60px;background:#0b0b12;padding:16px;margin:auto;justify-content:center}\n.elx-dots span{width:14px;height:14px;border-radius:50%;background:#8b5cf6;box-shadow:0 0 10px rgba(139,92,246,.6);animation:elx-dots-bounce 1.1s ease-in-out infinite}\n.elx-dots span:nth-child(2){background:#d946ef;box-shadow:0 0 10px rgba(217,70,239,.6);animation-delay:.18s}\n.elx-dots span:nth-child(3){background:#06b6d4;box-shadow:0 0 10px rgba(6,182,212,.6);animation-delay:.36s}\n@keyframes elx-dots-bounce{0%,60%,100%{transform:translateY(0);opacity:.7}30%{transform:translateY(-20px);opacity:1}}\n@media (prefers-reduced-motion:reduce){.elx-dots span{animation:none;opacity:1}.elx-dots span:nth-child(2){transform:translateY(-10px)}}","js":""},
  {"slug":"gradient-ring-elementa","title":"Gradient Ring","description":"Ein rotierender Ring mit einem fließenden Verlauf von Violett über Fuchsia zu Cyan erzeugt einen modernen, hochwertigen Ladeindikator vor dunklem Hintergrund.","framework":"css","tags":["loader","ring","gradient","dark","css"],"html":"&lt;div class=\"elx-gring\" role=\"status\" aria-label=\"Laden\"&gt;\n  &lt;div class=\"elx-gring__ring\"&gt;&lt;/div&gt;\n&lt;/div&gt;","css":".elx-gring{display:grid;place-items:center;width:80px;height:80px;background:#0b0b12;margin:auto}\n.elx-gring__ring{width:56px;height:56px;border-radius:50%;background:conic-gradient(from 0deg,#8b5cf6,#d946ef,#06b6d4,#8b5cf6);-webkit-mask:radial-gradient(farthest-side,transparent calc(100% - 7px),#000 calc(100% - 6px));mask:radial-gradient(farthest-side,transparent calc(100% - 7px),#000 calc(100% - 6px));animation:elx-gring-spin 1.1s linear infinite;filter:drop-shadow(0 0 6px rgba(139,92,246,.5))}\n@keyframes elx-gring-spin{to{transform:rotate(360deg)}}\n@media (prefers-reduced-motion:reduce){.elx-gring__ring{animation:none;opacity:.85}}","js":""},
  {"slug":"bar-equalizer-elementa","title":"Bar Equalizer","description":"Fünf vertikale Balken schwingen wie ein Audio-Equalizer in unterschiedlichen Rhythmen auf und ab und signalisieren so aktive Verarbeitung im dunklen Elementa-Look.","framework":"css","tags":["loader","equalizer","bars","dark","css"],"html":"&lt;div class=\"elx-eq\" role=\"status\" aria-label=\"Laden\"&gt;\n  &lt;span&gt;&lt;/span&gt;\n  &lt;span&gt;&lt;/span&gt;\n  &lt;span&gt;&lt;/span&gt;\n  &lt;span&gt;&lt;/span&gt;\n  &lt;span&gt;&lt;/span&gt;\n&lt;/div&gt;","css":".elx-eq{display:flex;gap:6px;align-items:center;height:64px;background:#0b0b12;padding:14px;margin:auto;justify-content:center}\n.elx-eq span{width:7px;height:14px;border-radius:4px;background:linear-gradient(180deg,#06b6d4,#8b5cf6);animation:elx-eq-move 1s ease-in-out infinite}\n.elx-eq span:nth-child(2){animation-delay:.15s;background:linear-gradient(180deg,#8b5cf6,#d946ef)}\n.elx-eq span:nth-child(3){animation-delay:.3s;background:linear-gradient(180deg,#d946ef,#8b5cf6)}\n.elx-eq span:nth-child(4){animation-delay:.45s;background:linear-gradient(180deg,#8b5cf6,#06b6d4)}\n.elx-eq span:nth-child(5){animation-delay:.6s;background:linear-gradient(180deg,#06b6d4,#d946ef)}\n@keyframes elx-eq-move{0%,100%{height:14px}50%{height:44px}}\n@media (prefers-reduced-motion:reduce){.elx-eq span{animation:none;height:28px}}","js":""},
  {"slug":"pulse-comet-elementa","title":"Pulse Comet","description":"Ein Kometen-Spinner zieht einen leuchtenden Schweif um einen sanft pulsierenden Kern und verbindet so Rotation und Puls zu einem auffälligen Ladeeffekt im Dark-Theme.","framework":"css","tags":["loader","comet","pulse","dark","css"],"html":"&lt;div class=\"elx-comet\" role=\"status\" aria-label=\"Laden\"&gt;\n  &lt;span class=\"elx-comet__pulse\"&gt;&lt;/span&gt;\n  &lt;span class=\"elx-comet__trail\"&gt;&lt;/span&gt;\n&lt;/div&gt;","css":".elx-comet{position:relative;width:74px;height:74px;display:grid;place-items:center;background:#0b0b12;margin:auto}\n.elx-comet__pulse{position:absolute;width:16px;height:16px;border-radius:50%;background:radial-gradient(circle at 35% 35%,#10b981,#06b6d4);animation:elx-comet-pulse 1.4s ease-in-out infinite}\n.elx-comet__trail{position:absolute;width:60px;height:60px;border-radius:50%;background:conic-gradient(from 0deg,transparent 0deg,transparent 200deg,#8b5cf6 300deg,#d946ef 360deg);-webkit-mask:radial-gradient(farthest-side,transparent calc(100% - 6px),#000 calc(100% - 5px));mask:radial-gradient(farthest-side,transparent calc(100% - 6px),#000 calc(100% - 5px));animation:elx-comet-spin .9s linear infinite}\n@keyframes elx-comet-spin{to{transform:rotate(360deg)}}\n@keyframes elx-comet-pulse{0%,100%{transform:scale(.8);box-shadow:0 0 6px rgba(16,185,129,.5)}50%{transform:scale(1.15);box-shadow:0 0 16px rgba(16,185,129,.8)}}\n@media (prefers-reduced-motion:reduce){.elx-comet__trail{animation:none;opacity:.8}.elx-comet__pulse{animation:none}}","js":""}
];

const INPUTS = [
  {"slug":"input-floating-label-violet","title":"Floating Label Input","description":"Ein Eingabefeld mit schwebendem Label, das beim Fokussieren oder bei Eingabe elegant nach oben skaliert. Violetter Fokus-Ring, abgerundete Ecken und ruhige Bewegung im Dark-Theme.","framework":"css","tags":["input","floating-label","dark","form","violet"],"html":"&lt;div class=\"fl-wrap\"&gt;\n  &lt;div class=\"fl-field\"&gt;\n    &lt;input class=\"fl-input\" id=\"fl-email\" type=\"email\" placeholder=\" \" required&gt;\n    &lt;label class=\"fl-label\" for=\"fl-email\"&gt;E-Mail-Adresse&lt;/label&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".fl-wrap{min-height:180px;display:flex;align-items:center;justify-content:center;background:#0b0b12;padding:24px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n.fl-field{position:relative;width:240px}\n.fl-input{width:100%;box-sizing:border-box;padding:19px 14px 7px;background:#14141f;border:1px solid #2a2a3a;border-radius:12px;color:#f4f4f8;font-size:15px;outline:none;transition:border-color .2s,box-shadow .2s}\n.fl-label{position:absolute;left:15px;top:15px;color:#8b8ba0;font-size:15px;pointer-events:none;transform-origin:left top;transition:transform .18s ease,color .18s ease}\n.fl-input:focus{border-color:#8b5cf6;box-shadow:0 0 0 3px rgba(139,92,246,.25)}\n.fl-input:focus+.fl-label,.fl-input:not(:placeholder-shown)+.fl-label{transform:translateY(-9px) scale(.75);color:#a78bfa}\n@media(prefers-reduced-motion:reduce){.fl-input,.fl-label{transition:none}}","js":""},
  {"slug":"input-glow-focus-fuchsia","title":"Glow on Focus Input","description":"Textfeld mit weichem, mehrschichtigem Leuchten in Fuchsia und Violett beim Fokussieren. Das Glühen lenkt die Aufmerksamkeit dezent auf das aktive Feld im dunklen Layout.","framework":"css","tags":["input","glow","focus","dark","fuchsia"],"html":"&lt;div class=\"glow-wrap\"&gt;\n  &lt;div class=\"glow-box\"&gt;\n    &lt;label class=\"glow-label\" for=\"glow-name\"&gt;Anzeigename&lt;/label&gt;\n    &lt;input class=\"glow-input\" id=\"glow-name\" type=\"text\" placeholder=\"Dein Name\"&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".glow-wrap{min-height:180px;display:flex;align-items:center;justify-content:center;background:#0b0b12;padding:24px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n.glow-box{width:240px}\n.glow-label{display:block;margin-bottom:8px;color:#c9c9d6;font-size:13px;font-weight:600;letter-spacing:.02em}\n.glow-input{width:100%;box-sizing:border-box;padding:12px 14px;background:#12121c;border:1px solid #2a2a3a;border-radius:12px;color:#f4f4f8;font-size:15px;outline:none;transition:border-color .25s,box-shadow .25s}\n.glow-input::placeholder{color:#6b6b80}\n.glow-input:focus{border-color:#d946ef;box-shadow:0 0 0 1px #d946ef,0 0 18px rgba(217,70,239,.45),0 0 40px rgba(139,92,246,.25)}\n@media(prefers-reduced-motion:reduce){.glow-input{transition:none}}","js":""},
  {"slug":"input-gradient-underline","title":"Animated Gradient Underline","description":"Minimalistisches Feld ohne Rahmen, dessen Unterstrich beim Fokussieren als Verlauf aus Violett, Fuchsia und Cyan von links nach rechts einfährt. Klar und modern im Dark-Theme.","framework":"css","tags":["input","underline","gradient","dark","animation"],"html":"&lt;div class=\"ul-wrap\"&gt;\n  &lt;div class=\"ul-field\"&gt;\n    &lt;label class=\"ul-label\" for=\"ul-user\"&gt;Benutzername&lt;/label&gt;\n    &lt;input class=\"ul-input\" id=\"ul-user\" type=\"text\" placeholder=\"benutzername\"&gt;\n    &lt;span class=\"ul-bar\" aria-hidden=\"true\"&gt;&lt;/span&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".ul-wrap{min-height:180px;display:flex;align-items:center;justify-content:center;background:#0b0b12;padding:24px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n.ul-field{position:relative;width:240px;padding-bottom:2px}\n.ul-label{display:block;margin-bottom:6px;color:#c9c9d6;font-size:13px;font-weight:600}\n.ul-input{width:100%;box-sizing:border-box;padding:10px 2px;background:transparent;border:none;border-bottom:2px solid #2a2a3a;color:#f4f4f8;font-size:15px;outline:none}\n.ul-input::placeholder{color:#6b6b80}\n.ul-bar{position:absolute;left:0;bottom:0;height:2px;width:100%;transform:scaleX(0);transform-origin:left;background:linear-gradient(90deg,#8b5cf6,#d946ef,#06b6d4);transition:transform .3s ease}\n.ul-input:focus~.ul-bar{transform:scaleX(1)}\n@media(prefers-reduced-motion:reduce){.ul-bar{transition:none}}","js":""},
  {"slug":"input-search-cyan-icon","title":"Search Field with CSS Icon","description":"Abgerundetes Suchfeld mit reiner CSS-Lupe als Icon, die beim Fokussieren auf Cyan umfärbt. Das Label ist visuell versteckt, bleibt aber für Screenreader vollständig zugänglich.","framework":"css","tags":["input","search","icon","dark","cyan"],"html":"&lt;div class=\"se-wrap\"&gt;\n  &lt;form class=\"se-form\" role=\"search\"&gt;\n    &lt;label class=\"se-label\" for=\"se-q\"&gt;Suche&lt;/label&gt;\n    &lt;span class=\"se-icon\" aria-hidden=\"true\"&gt;&lt;/span&gt;\n    &lt;input class=\"se-input\" id=\"se-q\" type=\"search\" placeholder=\"Suchen...\"&gt;\n  &lt;/form&gt;\n&lt;/div&gt;","css":".se-wrap{min-height:180px;display:flex;align-items:center;justify-content:center;background:#0b0b12;padding:24px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n.se-form{position:relative;width:240px}\n.se-label{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);border:0}\n.se-icon{position:absolute;left:16px;top:50%;transform:translateY(-50%);width:12px;height:12px;border:2px solid #8b8ba0;border-radius:50%;pointer-events:none;transition:border-color .2s}\n.se-icon::after{content:\"\";position:absolute;right:-5px;bottom:-4px;width:8px;height:2px;background:#8b8ba0;border-radius:2px;transform:rotate(45deg);transition:background .2s}\n.se-input{width:100%;box-sizing:border-box;padding:12px 16px 12px 40px;background:#14141f;border:1px solid #2a2a3a;border-radius:999px;color:#f4f4f8;font-size:15px;outline:none;transition:border-color .2s,box-shadow .2s}\n.se-input::placeholder{color:#6b6b80}\n.se-input:focus{border-color:#06b6d4;box-shadow:0 0 0 3px rgba(6,182,212,.22)}\n.se-form:focus-within .se-icon{border-color:#06b6d4}\n.se-form:focus-within .se-icon::after{background:#06b6d4}\n@media(prefers-reduced-motion:reduce){.se-icon,.se-icon::after,.se-input{transition:none}}","js":""},
  {"slug":"input-password-reveal-toggle","title":"Password Field with Reveal Toggle","description":"Passwortfeld mit umschaltbarem Auge-Button aus reinem CSS, der die Sichtbarkeit des Passworts steuert. Der Button nutzt aria-pressed und wechselnde Labels für volle Barrierefreiheit.","framework":"html","tags":["input","password","toggle","dark","accessible"],"html":"&lt;div class=\"pw-wrap\"&gt;\n  &lt;div class=\"pw-field\"&gt;\n    &lt;label class=\"pw-label\" for=\"pw-in\"&gt;Passwort&lt;/label&gt;\n    &lt;div class=\"pw-row\"&gt;\n      &lt;input class=\"pw-input\" id=\"pw-in\" type=\"password\" placeholder=\"••••••••\"&gt;\n      &lt;button class=\"pw-toggle\" type=\"button\" aria-label=\"Passwort anzeigen\" aria-pressed=\"false\"&gt;\n        &lt;span class=\"pw-eye\" aria-hidden=\"true\"&gt;&lt;/span&gt;\n      &lt;/button&gt;\n    &lt;/div&gt;\n  &lt;/div&gt;\n&lt;/div&gt;","css":".pw-wrap{min-height:180px;display:flex;align-items:center;justify-content:center;background:#0b0b12;padding:24px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n.pw-field{width:240px}\n.pw-label{display:block;margin-bottom:8px;color:#c9c9d6;font-size:13px;font-weight:600}\n.pw-row{position:relative}\n.pw-input{width:100%;box-sizing:border-box;padding:12px 46px 12px 14px;background:#12121c;border:1px solid #2a2a3a;border-radius:12px;color:#f4f4f8;font-size:15px;letter-spacing:.05em;outline:none;transition:border-color .2s,box-shadow .2s}\n.pw-input::placeholder{color:#6b6b80;letter-spacing:.15em}\n.pw-input:focus{border-color:#8b5cf6;box-shadow:0 0 0 3px rgba(139,92,246,.25)}\n.pw-toggle{position:absolute;right:6px;top:50%;transform:translateY(-50%);width:34px;height:34px;display:flex;align-items:center;justify-content:center;background:transparent;border:none;border-radius:8px;cursor:pointer}\n.pw-toggle:focus-visible{outline:2px solid #06b6d4;outline-offset:2px}\n.pw-eye{position:relative;display:block;width:16px;height:16px;border:2px solid #b9a6f5;border-radius:50%;box-sizing:border-box}\n.pw-eye::before{content:\"\";position:absolute;left:50%;top:50%;width:6px;height:6px;background:#b9a6f5;border-radius:50%;transform:translate(-50%,-50%)}\n.pw-toggle[aria-pressed=\"true\"] .pw-eye::after{content:\"\";position:absolute;left:-3px;top:6px;width:22px;height:2px;background:#b9a6f5;border-radius:2px;transform:rotate(-45deg)}","js":"document.querySelectorAll('.pw-toggle').forEach(function(b){b.addEventListener('click',function(){var i=b.parentElement.querySelector('.pw-input');var reveal=i.type==='password';i.type=reveal?'text':'password';b.setAttribute('aria-pressed',reveal?'true':'false');b.setAttribute('aria-label',reveal?'Passwort verbergen':'Passwort anzeigen');});});"}
];

const TOGGLES = [
  {"slug":"gradient-brand-toggle","title":"Gradient Brand Toggle","description":"Eleganter Umschalter mit einem lebendigen Marken-Verlauf von Violett über Fuchsia zu Cyan im aktiven Zustand, weichem Glow und vollständig per Tastatur bedienbarer Checkbox.","framework":"css","tags":["toggle","switch","gradient","dark","accessible"],"html":"&lt;div class=\"el-grad-wrap\"&gt;\n  &lt;label class=\"el-grad-toggle\" aria-label=\"Gradient umschalten\"&gt;\n    &lt;input type=\"checkbox\" checked&gt;\n    &lt;span class=\"el-grad-track\"&gt;&lt;span class=\"el-grad-knob\"&gt;&lt;/span&gt;&lt;/span&gt;\n  &lt;/label&gt;\n&lt;/div&gt;","css":".el-grad-wrap{display:flex;align-items:center;justify-content:center;min-height:90px}\n.el-grad-toggle{display:inline-flex;cursor:pointer;-webkit-tap-highlight-color:transparent}\n.el-grad-toggle input{position:absolute;width:1px;height:1px;opacity:0;margin:0}\n.el-grad-track{position:relative;width:60px;height:32px;border-radius:999px;background:#17171f;border:1px solid #2a2a3a;transition:background .35s ease,box-shadow .35s ease}\n.el-grad-knob{position:absolute;top:3px;left:3px;width:24px;height:24px;border-radius:50%;background:#e8e8f2;box-shadow:0 2px 4px rgba(0,0,0,.4);transition:transform .35s cubic-bezier(.34,1.4,.5,1)}\n.el-grad-toggle input:checked+.el-grad-track{background:linear-gradient(90deg,#8b5cf6,#d946ef,#06b6d4);box-shadow:0 0 14px rgba(217,70,239,.45)}\n.el-grad-toggle input:checked+.el-grad-track .el-grad-knob{transform:translateX(28px)}\n.el-grad-toggle input:focus-visible+.el-grad-track{outline:2px solid #06b6d4;outline-offset:3px}\n@media (prefers-reduced-motion:reduce){.el-grad-track,.el-grad-knob{transition:none}}","js":""},
  {"slug":"ios-style-toggle","title":"iOS Style Toggle","description":"Klassischer, minimalistischer Schalter im iOS-Stil mit weißem Knopf und sanfter Feder-Animation, der im aktivierten Zustand in der Erfolgsfarbe Grün leuchtet.","framework":"css","tags":["toggle","switch","ios","minimal","dark"],"html":"&lt;div class=\"el-ios-wrap\"&gt;\n  &lt;label class=\"el-ios-toggle\" aria-label=\"Einstellung umschalten\"&gt;\n    &lt;input type=\"checkbox\"&gt;\n    &lt;span class=\"el-ios-track\"&gt;&lt;span class=\"el-ios-knob\"&gt;&lt;/span&gt;&lt;/span&gt;\n  &lt;/label&gt;\n&lt;/div&gt;","css":".el-ios-wrap{display:flex;align-items:center;justify-content:center;min-height:90px}\n.el-ios-toggle{display:inline-flex;cursor:pointer;-webkit-tap-highlight-color:transparent}\n.el-ios-toggle input{position:absolute;width:1px;height:1px;opacity:0;margin:0}\n.el-ios-track{position:relative;width:56px;height:32px;border-radius:999px;background:#3a3a4c;transition:background .3s ease}\n.el-ios-knob{position:absolute;top:2px;left:2px;width:28px;height:28px;border-radius:50%;background:#ffffff;box-shadow:0 2px 5px rgba(0,0,0,.45);transition:transform .3s cubic-bezier(.4,0,.2,1)}\n.el-ios-toggle input:checked+.el-ios-track{background:#10b981}\n.el-ios-toggle input:checked+.el-ios-track .el-ios-knob{transform:translateX(24px)}\n.el-ios-toggle input:focus-visible+.el-ios-track{outline:2px solid #10b981;outline-offset:3px}\n@media (prefers-reduced-motion:reduce){.el-ios-knob,.el-ios-track{transition:none}}","js":""},
  {"slug":"day-night-toggle","title":"Day and Night Toggle","description":"Verspielter Tag-Nacht-Umschalter, der einen Mond mit Sternenhimmel in eine leuchtende Sonne vor einem Violett-Cyan-Verlauf verwandelt, komplett in reinem CSS umgesetzt.","framework":"css","tags":["toggle","switch","daynight","theme","dark"],"html":"&lt;div class=\"el-dn-wrap\"&gt;\n  &lt;label class=\"el-dn-toggle\" aria-label=\"Tag- und Nachtmodus umschalten\"&gt;\n    &lt;input type=\"checkbox\"&gt;\n    &lt;span class=\"el-dn-track\"&gt;&lt;span class=\"el-dn-knob\"&gt;&lt;/span&gt;&lt;/span&gt;\n  &lt;/label&gt;\n&lt;/div&gt;","css":".el-dn-wrap{display:flex;align-items:center;justify-content:center;min-height:90px}\n.el-dn-toggle{display:inline-flex;cursor:pointer;-webkit-tap-highlight-color:transparent}\n.el-dn-toggle input{position:absolute;width:1px;height:1px;opacity:0;margin:0}\n.el-dn-track{position:relative;width:64px;height:32px;border-radius:999px;background:#12142e;border:1px solid #262a52;overflow:hidden;transition:background .45s ease}\n.el-dn-track::before{content:\"\";position:absolute;top:8px;right:13px;width:2px;height:2px;border-radius:50%;background:#fff;box-shadow:6px 5px 0 #fff,12px -2px 0 #cfd2ff,-3px 9px 0 #fff;transition:opacity .35s ease}\n.el-dn-knob{position:absolute;top:4px;left:4px;width:24px;height:24px;border-radius:50%;background:#dfe2ff;box-shadow:inset -6px -3px 0 0 #12142e;transition:transform .45s cubic-bezier(.4,0,.2,1),background .45s ease,box-shadow .45s ease}\n.el-dn-toggle input:checked+.el-dn-track{background:linear-gradient(90deg,#8b5cf6,#06b6d4)}\n.el-dn-toggle input:checked+.el-dn-track::before{opacity:0}\n.el-dn-toggle input:checked+.el-dn-track .el-dn-knob{transform:translateX(32px);background:#ffffff;box-shadow:0 0 8px 2px rgba(255,255,255,.85),0 0 14px 4px rgba(6,182,212,.6)}\n.el-dn-toggle input:focus-visible+.el-dn-track{outline:2px solid #8b5cf6;outline-offset:3px}\n@media (prefers-reduced-motion:reduce){.el-dn-knob,.el-dn-track,.el-dn-track::before{transition:none}}","js":""},
  {"slug":"neon-glow-toggle","title":"Neon Glow Toggle","description":"Dunkler Umschalter mit Neon-Ästhetik, der im aktiven Zustand einen leuchtenden Cyan-Rahmen sowie einen glimmenden Knopf zeigt und im Fokus violett hervorgehoben wird.","framework":"css","tags":["toggle","switch","neon","glow","dark"],"html":"&lt;div class=\"el-neon-wrap\"&gt;\n  &lt;label class=\"el-neon-toggle\" aria-label=\"Neon umschalten\"&gt;\n    &lt;input type=\"checkbox\" checked&gt;\n    &lt;span class=\"el-neon-track\"&gt;&lt;span class=\"el-neon-knob\"&gt;&lt;/span&gt;&lt;/span&gt;\n  &lt;/label&gt;\n&lt;/div&gt;","css":".el-neon-wrap{display:flex;align-items:center;justify-content:center;min-height:90px}\n.el-neon-toggle{display:inline-flex;cursor:pointer;-webkit-tap-highlight-color:transparent}\n.el-neon-toggle input{position:absolute;width:1px;height:1px;opacity:0;margin:0}\n.el-neon-track{position:relative;width:58px;height:30px;border-radius:999px;background:#0d0d17;border:1px solid #2a2a3a;transition:border-color .3s ease,box-shadow .3s ease}\n.el-neon-knob{position:absolute;top:3px;left:3px;width:22px;height:22px;border-radius:50%;background:#3a3a4c;transition:transform .3s ease,background .3s ease,box-shadow .3s ease}\n.el-neon-toggle input:checked+.el-neon-track{border-color:#06b6d4;box-shadow:0 0 10px rgba(6,182,212,.7),inset 0 0 8px rgba(6,182,212,.35)}\n.el-neon-toggle input:checked+.el-neon-track .el-neon-knob{transform:translateX(28px);background:#06b6d4;box-shadow:0 0 8px #06b6d4,0 0 14px rgba(6,182,212,.8)}\n.el-neon-toggle input:focus-visible+.el-neon-track{outline:2px solid #d946ef;outline-offset:3px}\n@media (prefers-reduced-motion:reduce){.el-neon-knob,.el-neon-track{transition:none}}","js":""},
  {"slug":"pill-text-toggle","title":"Pill Text Toggle","description":"Pillenförmiger Schalter mit sichtbaren Statustexten AN und AUS, der im aktiven Zustand in einem Violett-Fuchsia-Verlauf erstrahlt und barrierefrei bedienbar bleibt.","framework":"css","tags":["toggle","switch","pill","label","dark"],"html":"&lt;div class=\"el-pill-wrap\"&gt;\n  &lt;label class=\"el-pill-toggle\" aria-label=\"An oder Aus\"&gt;\n    &lt;input type=\"checkbox\"&gt;\n    &lt;span class=\"el-pill-track\"&gt;\n      &lt;span class=\"el-pill-on\"&gt;AN&lt;/span&gt;\n      &lt;span class=\"el-pill-off\"&gt;AUS&lt;/span&gt;\n      &lt;span class=\"el-pill-knob\"&gt;&lt;/span&gt;\n    &lt;/span&gt;\n  &lt;/label&gt;\n&lt;/div&gt;","css":".el-pill-wrap{display:flex;align-items:center;justify-content:center;min-height:90px}\n.el-pill-toggle{display:inline-flex;cursor:pointer;-webkit-tap-highlight-color:transparent}\n.el-pill-toggle input{position:absolute;width:1px;height:1px;opacity:0;margin:0}\n.el-pill-track{position:relative;display:inline-flex;align-items:center;width:74px;height:32px;border-radius:999px;background:#1c1c2a;border:1px solid #2f2f42;transition:background .35s ease}\n.el-pill-on,.el-pill-off{position:absolute;font:600 11px/1 system-ui,-apple-system,sans-serif;letter-spacing:.06em;transition:opacity .3s ease}\n.el-pill-on{left:12px;color:#ffffff;opacity:0}\n.el-pill-off{right:10px;color:#83839a;opacity:1}\n.el-pill-knob{position:absolute;top:3px;left:3px;width:26px;height:26px;border-radius:50%;background:#e8e8f2;box-shadow:0 2px 4px rgba(0,0,0,.4);transition:transform .35s cubic-bezier(.4,0,.2,1)}\n.el-pill-toggle input:checked+.el-pill-track{background:linear-gradient(90deg,#8b5cf6,#d946ef)}\n.el-pill-toggle input:checked+.el-pill-track .el-pill-on{opacity:1}\n.el-pill-toggle input:checked+.el-pill-track .el-pill-off{opacity:0}\n.el-pill-toggle input:checked+.el-pill-track .el-pill-knob{transform:translateX(42px)}\n.el-pill-toggle input:focus-visible+.el-pill-track{outline:2px solid #8b5cf6;outline-offset:3px}\n@media (prefers-reduced-motion:reduce){.el-pill-knob,.el-pill-on,.el-pill-off,.el-pill-track{transition:none}}","js":""}
];

const BACKGROUNDS = [
  {"slug":"aurora-flow-background","title":"Aurora Flow","description":"Ein sanft fließender Aurora-Verlauf aus Violett, Fuchsia und Cyan, der wie Polarlichter über einen dunklen Nachthimmel wandert und dabei GPU-schonend nur Transform und Opacity animiert.","framework":"css","tags":["aurora","gradient","dark","glow","animated"],"html":"&lt;div class=\"aurora-bg\"&gt;\n  &lt;div class=\"aurora-layer aurora-1\"&gt;&lt;/div&gt;\n  &lt;div class=\"aurora-layer aurora-2\"&gt;&lt;/div&gt;\n  &lt;div class=\"aurora-layer aurora-3\"&gt;&lt;/div&gt;\n&lt;/div&gt;","css":".aurora-bg {\n  position: relative;\n  width: 100%;\n  max-width: 320px;\n  height: 180px;\n  border-radius: 16px;\n  overflow: hidden;\n  background: #0a0a12;\n}\n.aurora-layer {\n  position: absolute;\n  width: 200%;\n  height: 200%;\n  top: -50%;\n  left: -50%;\n  border-radius: 45%;\n  filter: blur(30px);\n  opacity: 0.55;\n  will-change: transform;\n}\n.aurora-1 {\n  background: radial-gradient(circle at 30% 40%, #8b5cf6, transparent 60%);\n  animation: aurora-spin-a 12s linear infinite;\n}\n.aurora-2 {\n  background: radial-gradient(circle at 70% 60%, #d946ef, transparent 60%);\n  animation: aurora-spin-b 16s linear infinite;\n}\n.aurora-3 {\n  background: radial-gradient(circle at 50% 50%, #06b6d4, transparent 55%);\n  animation: aurora-spin-a 20s linear infinite reverse;\n}\n@keyframes aurora-spin-a {\n  from { transform: rotate(0deg) translateX(6%); }\n  to { transform: rotate(360deg) translateX(6%); }\n}\n@keyframes aurora-spin-b {\n  from { transform: rotate(0deg) translateX(-8%); }\n  to { transform: rotate(-360deg) translateX(-8%); }\n}\n@media (prefers-reduced-motion: reduce) {\n  .aurora-layer { animation: none; }\n}","js":""},
  {"slug":"mesh-gradient-morph","title":"Mesh Gradient Morph","description":"Ein animierter Mesh-Gradient, bei dem mehrere farbige Lichtpunkte in Violett, Fuchsia und Cyan sanft ihre Position wechseln und so einen lebendig morphenden Farbverlauf im Dark-Theme erzeugen.","framework":"css","tags":["mesh","gradient","morph","dark","colorful"],"html":"&lt;div class=\"mesh-bg\"&gt;\n  &lt;span class=\"mesh-dot mesh-a\"&gt;&lt;/span&gt;\n  &lt;span class=\"mesh-dot mesh-b\"&gt;&lt;/span&gt;\n  &lt;span class=\"mesh-dot mesh-c\"&gt;&lt;/span&gt;\n  &lt;span class=\"mesh-dot mesh-d\"&gt;&lt;/span&gt;\n&lt;/div&gt;","css":".mesh-bg {\n  position: relative;\n  width: 100%;\n  max-width: 320px;\n  height: 180px;\n  border-radius: 16px;\n  overflow: hidden;\n  background: #0b0710;\n}\n.mesh-dot {\n  position: absolute;\n  width: 160px;\n  height: 160px;\n  border-radius: 50%;\n  filter: blur(38px);\n  opacity: 0.7;\n  will-change: transform;\n}\n.mesh-a { background: #8b5cf6; top: -30px; left: -20px; animation: mesh-move-a 14s ease-in-out infinite; }\n.mesh-b { background: #d946ef; bottom: -40px; right: -20px; animation: mesh-move-b 18s ease-in-out infinite; }\n.mesh-c { background: #06b6d4; top: 20px; right: -30px; animation: mesh-move-c 16s ease-in-out infinite; }\n.mesh-d { background: #10b981; bottom: -30px; left: 20px; animation: mesh-move-a 20s ease-in-out infinite reverse; }\n@keyframes mesh-move-a {\n  0%,100% { transform: translate(0,0); }\n  50% { transform: translate(40px, 30px); }\n}\n@keyframes mesh-move-b {\n  0%,100% { transform: translate(0,0); }\n  50% { transform: translate(-45px, -25px); }\n}\n@keyframes mesh-move-c {\n  0%,100% { transform: translate(0,0); }\n  50% { transform: translate(-30px, 40px); }\n}\n@media (prefers-reduced-motion: reduce) {\n  .mesh-dot { animation: none; }\n}","js":""},
  {"slug":"neon-grid-pulse","title":"Neon Grid Pulse","description":"Ein leuchtendes Neon-Raster mit perspektivischer Tiefe, das im Rhythmus nach oben scrollt und dabei in Cyan und Violett pulsiert, um einen futuristischen Synthwave-Look im Dark-Theme zu erzeugen.","framework":"css","tags":["grid","neon","synthwave","dark","retro"],"html":"&lt;div class=\"grid-bg\"&gt;\n  &lt;div class=\"grid-plane\"&gt;&lt;/div&gt;\n  &lt;div class=\"grid-glow\"&gt;&lt;/div&gt;\n&lt;/div&gt;","css":".grid-bg {\n  position: relative;\n  width: 100%;\n  max-width: 320px;\n  height: 180px;\n  border-radius: 16px;\n  overflow: hidden;\n  background: linear-gradient(180deg, #0a0715 0%, #130a24 100%);\n  perspective: 200px;\n}\n.grid-plane {\n  position: absolute;\n  left: -50%;\n  top: 40%;\n  width: 200%;\n  height: 160%;\n  background-image:\n    linear-gradient(#8b5cf6 1px, transparent 1px),\n    linear-gradient(90deg, #06b6d4 1px, transparent 1px);\n  background-size: 32px 32px;\n  transform: rotateX(70deg);\n  transform-origin: top center;\n  opacity: 0.55;\n  animation: grid-scroll 4s linear infinite;\n  will-change: background-position;\n}\n.grid-glow {\n  position: absolute;\n  inset: 0;\n  background: radial-gradient(ellipse at 50% 60%, rgba(217,70,239,0.35), transparent 60%);\n  animation: grid-pulse 3s ease-in-out infinite;\n}\n@keyframes grid-scroll {\n  from { background-position: 0 0; }\n  to { background-position: 0 32px; }\n}\n@keyframes grid-pulse {\n  0%,100% { opacity: 0.5; }\n  50% { opacity: 0.9; }\n}\n@media (prefers-reduced-motion: reduce) {\n  .grid-plane, .grid-glow { animation: none; }\n}","js":""},
  {"slug":"starfield-drift","title":"Starfield Drift","description":"Ein ruhiges Sternenfeld aus reinen CSS-Partikeln, das in mehreren Ebenen langsam nach oben driftet und mit sanft funkelnden Lichtpunkten in Weiß und Cyan eine tiefe Weltraum-Atmosphäre schafft.","framework":"css","tags":["stars","particles","space","dark","twinkle"],"html":"&lt;div class=\"star-bg\"&gt;\n  &lt;div class=\"star-layer star-far\"&gt;&lt;/div&gt;\n  &lt;div class=\"star-layer star-near\"&gt;&lt;/div&gt;\n&lt;/div&gt;","css":".star-bg {\n  position: relative;\n  width: 100%;\n  max-width: 320px;\n  height: 180px;\n  border-radius: 16px;\n  overflow: hidden;\n  background: radial-gradient(ellipse at 50% 30%, #16122b 0%, #06040d 100%);\n}\n.star-layer {\n  position: absolute;\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 200%;\n  will-change: transform;\n}\n.star-far {\n  background-image:\n    radial-gradient(1px 1px at 20px 30px, #ffffff, transparent),\n    radial-gradient(1px 1px at 80px 90px, #06b6d4, transparent),\n    radial-gradient(1px 1px at 140px 50px, #ffffff, transparent),\n    radial-gradient(1px 1px at 200px 120px, #8b5cf6, transparent),\n    radial-gradient(1px 1px at 260px 70px, #ffffff, transparent);\n  background-size: 300px 150px;\n  animation: star-drift 30s linear infinite, star-twinkle 4s ease-in-out infinite;\n}\n.star-near {\n  background-image:\n    radial-gradient(1.5px 1.5px at 50px 60px, #ffffff, transparent),\n    radial-gradient(1.5px 1.5px at 120px 20px, #d946ef, transparent),\n    radial-gradient(1.5px 1.5px at 180px 100px, #ffffff, transparent),\n    radial-gradient(1.5px 1.5px at 240px 40px, #06b6d4, transparent);\n  background-size: 300px 180px;\n  animation: star-drift 18s linear infinite, star-twinkle 3s ease-in-out infinite;\n}\n@keyframes star-drift {\n  from { transform: translateY(0); }\n  to { transform: translateY(-50%); }\n}\n@keyframes star-twinkle {\n  0%,100% { opacity: 0.5; }\n  50% { opacity: 1; }\n}\n@media (prefers-reduced-motion: reduce) {\n  .star-layer { animation: none; }\n}","js":""},
  {"slug":"floating-blobs-glow","title":"Floating Blobs Glow","description":"Weich leuchtende Gradient-Blobs in Fuchsia, Violett und Erfolgsgrün, die organisch durch den dunklen Raum schweben und dabei ihre Form leicht verändern, um eine beruhigende, moderne Tiefe zu erzeugen.","framework":"css","tags":["blobs","glow","floating","dark","organic"],"html":"&lt;div class=\"blob-bg\"&gt;\n  &lt;span class=\"blob blob-1\"&gt;&lt;/span&gt;\n  &lt;span class=\"blob blob-2\"&gt;&lt;/span&gt;\n  &lt;span class=\"blob blob-3\"&gt;&lt;/span&gt;\n&lt;/div&gt;","css":".blob-bg {\n  position: relative;\n  width: 100%;\n  max-width: 320px;\n  height: 180px;\n  border-radius: 16px;\n  overflow: hidden;\n  background: #08060f;\n}\n.blob {\n  position: absolute;\n  width: 120px;\n  height: 120px;\n  border-radius: 42% 58% 63% 37% / 41% 44% 56% 59%;\n  filter: blur(24px);\n  opacity: 0.65;\n  will-change: transform;\n}\n.blob-1 {\n  background: #d946ef;\n  top: 10px;\n  left: 10px;\n  animation: blob-float-1 13s ease-in-out infinite;\n}\n.blob-2 {\n  background: #8b5cf6;\n  bottom: -10px;\n  right: 20px;\n  animation: blob-float-2 17s ease-in-out infinite;\n}\n.blob-3 {\n  background: #10b981;\n  top: 40px;\n  right: -10px;\n  animation: blob-float-1 21s ease-in-out infinite reverse;\n}\n@keyframes blob-float-1 {\n  0%,100% { transform: translate(0,0) scale(1); }\n  33% { transform: translate(30px, 20px) scale(1.1); }\n  66% { transform: translate(-20px, 30px) scale(0.95); }\n}\n@keyframes blob-float-2 {\n  0%,100% { transform: translate(0,0) scale(1); }\n  50% { transform: translate(-35px, -25px) scale(1.15); }\n}\n@media (prefers-reduced-motion: reduce) {\n  .blob { animation: none; }\n}","js":""}
];

const GROUPS = [
  ["buttons", BUTTONS, "pass"],
  ["cards", CARDS, "unchecked"],
  ["loaders", LOADERS, "unchecked"],
  ["inputs", INPUTS, "pass"],
  ["toggles", TOGGLES, "pass"],
  ["backgrounds", BACKGROUNDS, "unchecked"],
];

let created = 0, failed = 0;
const now = Date.now();
let idx = 0;

for (const [category, list, a11y] of GROUPS) {
  console.log(`\n-> ${category}: ${list.length}`);
  for (const c of list) {
    idx++;
    const base = {
      title: c.title,
      description: c.description,
      html: unesc(c.html),
      css: unesc(c.css),
      js: unesc(c.js),
      framework: c.framework,
      category,
      tags: c.tags,
      authorId: AUTHOR_ID,
      authorUsername: AUTHOR_NAME,
      likesCount: 0,
      views: 0,
      a11y,
      createdAt: new Date(now - idx * 60000).toISOString(),
    };
    let done = false;
    for (let attempt = 0; attempt < 3 && !done; attempt++) {
      const slug = attempt === 0 ? c.slug : `${c.slug}-${attempt + 1}`;
      try {
        await db.createDocument(DB, COL, ID.unique(), { ...base, slug }, perms);
        console.log("  ok", slug);
        created++; done = true;
      } catch (e) {
        if (e?.code === 409) continue;
        console.error("  fail", c.slug, "->", e.message);
        failed++; done = true;
      }
    }
  }
}

console.log(`\nFertig. Erstellt: ${created}, Fehler: ${failed}`);
